#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 23, 2022 03:33:15 PM EEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import edit_figure_support , edit_params_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x600+376+151")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("Edit figure")
        top.configure(background="#6bbed6")
        top.iconbitmap("chart.ico")

        self.top = top
        self.combobox_1 = tk.StringVar()
        self.combobox_2 = tk.StringVar()
        self.combobox_3 = tk.StringVar()

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.0, height=51, width=604)
        self.Label1.configure(background="#008080")
        self.Label1.configure(compound='center')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Times New Roman} -size 22 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Figure editor''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.25, rely=0.156, height=41, width=74)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#6bbed6")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Figsize''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.417, rely=0.178, height=20, relwidth=0.29)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label2_1 = tk.Label(self.top)
        self.Label2_1.place(relx=0.25, rely=0.267, height=41, width=74)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#6bbed6")
        self.Label2_1.configure(compound='left')
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''DPI''')

        self.Entry1_1 = tk.Entry(self.top)
        self.Entry1_1.place(relx=0.417, rely=0.289, height=20, relwidth=0.29)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1.configure(selectforeground="black")

        self.Label2_2 = tk.Label(self.top)
        self.Label2_2.place(relx=0.15, rely=0.378, height=41, width=222)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(anchor='w')
        self.Label2_2.configure(background="#6bbed6")
        self.Label2_2.configure(compound='left')
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Facecolor , Edgecolor''')

        self.Entry1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1.place(relx=0.56, rely=0.4, height=20, relwidth=0.29)
        self.Entry1_1_1.configure(background="white")
        self.Entry1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1.configure(foreground="#000000")
        self.Entry1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1.configure(insertbackground="black")
        self.Entry1_1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1_1.configure(selectforeground="black")

        self.Label2_2_1 = tk.Label(self.top)
        self.Label2_2_1.place(relx=0.22, rely=0.489, height=41, width=94)
        self.Label2_2_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1.configure(anchor='w')
        self.Label2_2_1.configure(background="#6bbed6")
        self.Label2_2_1.configure(compound='left')
        self.Label2_2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_2_1.configure(foreground="#000000")
        self.Label2_2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1.configure(highlightcolor="black")
        self.Label2_2_1.configure(text='''Frameon''')

        self.TCombobox1 = ttk.Combobox(self.top)
        self.TCombobox1.place(relx=0.417, rely=0.511, relheight=0.047
                , relwidth=0.288)
        self.value_list = ['True','False',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=self.combobox_1)
        self.TCombobox1.configure(takefocus="")
        self.TCombobox1.configure(font="-family {Times New Roman} -size 8 ")

        self.Label2_2_1_1 = tk.Label(self.top)
        self.Label2_2_1_1.place(relx=0.2, rely=0.844, height=41, width=153)
        self.Label2_2_1_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1_1.configure(background="#6bbed6")
        self.Label2_2_1_1.configure(compound='left')
        self.Label2_2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1_1.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_2_1_1.configure(foreground="#000000")
        self.Label2_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1_1.configure(highlightcolor="black")
        self.Label2_2_1_1.configure(text='''SubplotParams''')


        self.Button1 = tk.Button(self.top , command=edit_params_support.main)
        self.Button1.place(relx=0.5, rely=0.844, height=34, width=177)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='center')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Edit params''')

        self.Label2_2_1_2 = tk.Label(self.top)
        self.Label2_2_1_2.place(relx=0.18, rely=0.6, height=41, width=129)
        self.Label2_2_1_2.configure(activebackground="#f9f9f9")
        self.Label2_2_1_2.configure(anchor='w')
        self.Label2_2_1_2.configure(background="#6bbed6")
        self.Label2_2_1_2.configure(compound='left')
        self.Label2_2_1_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1_2.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_2_1_2.configure(foreground="#000000")
        self.Label2_2_1_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1_2.configure(highlightcolor="black")
        self.Label2_2_1_2.configure(text='''Tight_layout''')

        self.TCombobox1_1 = ttk.Combobox(self.top)
        self.TCombobox1_1.place(relx=0.417, rely=0.622, relheight=0.047
                , relwidth=0.288)
        self.value_list = ['True','False',]
        self.TCombobox1_1.configure(values=self.value_list)
        self.TCombobox1_1.configure(textvariable=self.combobox_2)
        self.TCombobox1_1.configure(takefocus="")
        self.TCombobox1_1.configure(font="-family {Times New Roman} -size 8 ")

        self.Label2_2_1_2_1 = tk.Label(self.top)
        self.Label2_2_1_2_1.place(relx=0.14, rely=0.711, height=41, width=200)
        self.Label2_2_1_2_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1_2_1.configure(anchor='w')
        self.Label2_2_1_2_1.configure(background="#6bbed6")
        self.Label2_2_1_2_1.configure(compound='left')
        self.Label2_2_1_2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1_2_1.configure(font="-family {Times New Roman} -size 14 -weight bold")
        self.Label2_2_1_2_1.configure(foreground="#000000")
        self.Label2_2_1_2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1_2_1.configure(highlightcolor="black")
        self.Label2_2_1_2_1.configure(text='''Constrained_layout''')

        self.TCombobox1_1_1 = ttk.Combobox(self.top)
        self.TCombobox1_1_1.place(relx=0.5, rely=0.733, relheight=0.047
                , relwidth=0.288)
        self.value_list = ['True','False',]
        self.TCombobox1_1_1.configure(values=self.value_list)
        self.TCombobox1_1_1.configure(textvariable=self.combobox_3)
        self.TCombobox1_1_1.configure(takefocus="")
        self.TCombobox1_1_1.configure(font="-family {Times New Roman} -size 8 ")


        def properties_to_plot():

            self.top.destroy()
            str_str = str(self.Entry1_1_1.get())
            x = str_str.split(",")
            
            global dictinary_figure

            dictinary_figure={
                'figsize' :  tuple(map(float, str(self.Entry1.get()).split(','))) ,
                'dpi' : float(self.Entry1_1.get()) ,
                'facecolor' : x[0] ,
                'edgecolor' : x[1] ,
                'frameon' : bool(self.TCombobox1.get()) ,
                'tight_layout' : bool(self.TCombobox1_1.get()) ,
                'constrained_layout' : bool(self.TCombobox1_1_1.get()) ,
                
            }

            try:
               txt_file = open('dictionary_figure.txt', 'wt')
               txt_file.write(str(dictinary_figure))
               txt_file.close()
  
            except:
                tk.messagebox.showerror("Error" , "Unable to write to file !")
            
            
        self.Button1 = tk.Button(self.top , command=properties_to_plot)
        self.Button1.place(relx=0.5, rely=0.97, height=34, width=177 , anchor="center" )
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(compound='center')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Properties to Plot''')


def start_up():
    edit_figure_support.main()

if __name__ == '__main__':
    edit_figure_support.main()




