#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 23, 2022 05:14:37 PM EEST  platform: Windows NT

import sys
import tkinter.ttk as ttk
from tkinter.constants import *
import edit_params
from tkinter import messagebox
import tkinter as tk

def main(*args):
   '''Main entry point for the application.'''
   global root
   try:
        if root.state() == "normal": 
            root.focus()
   except :
    root = tk.Tk()
    def on_closing():
     if tk.messagebox.askokcancel("Quit Edit Params", "Do you want to quit?"):
        root.destroy()
    root.protocol( 'WM_DELETE_WINDOW' , on_closing)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = edit_params.Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    edit_params.start_up()




