#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 23, 2022 05:14:27 PM EEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import edit_params_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("619x467+364+89")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(0,  0)
        top.title("Edit params")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.iconbitmap("chart.ico")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.0, height=64, width=623)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#73a7ce")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Times New Roman} -size 22 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Parameters Editor''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.307, rely=0.214, height=22, width=45)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Times New Roman} -size 14")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Left''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.467, rely=0.214, height=20, relwidth=0.2)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Label2_1 = tk.Label(self.top)
        self.Label2_1.place(relx=0.307, rely=0.321, height=22, width=56)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(compound='left')
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Times New Roman} -size 14")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Right''')

        self.Entry1_1 = tk.Entry(self.top)
        self.Entry1_1.place(relx=0.467, rely=0.321, height=20, relwidth=0.2)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1.configure(selectforeground="black")

        self.Label2_2 = tk.Label(self.top)
        self.Label2_2.place(relx=0.307, rely=0.428, height=22, width=71)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(anchor='w')
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(compound='left')
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font="-family {Times New Roman} -size 14")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Bottom''')

        self.Entry1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1.place(relx=0.467, rely=0.428, height=20, relwidth=0.2)
        self.Entry1_1_1.configure(background="white")
        self.Entry1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1.configure(foreground="#000000")
        self.Entry1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1.configure(insertbackground="black")
        self.Entry1_1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1_1.configure(selectforeground="black")

        self.Label2_2_1 = tk.Label(self.top)
        self.Label2_2_1.place(relx=0.307, rely=0.535, height=22, width=45)
        self.Label2_2_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1.configure(anchor='w')
        self.Label2_2_1.configure(background="#d9d9d9")
        self.Label2_2_1.configure(compound='left')
        self.Label2_2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1.configure(font="-family {Times New Roman} -size 14")
        self.Label2_2_1.configure(foreground="#000000")
        self.Label2_2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1.configure(highlightcolor="black")
        self.Label2_2_1.configure(text='''Top''')

        self.Entry1_1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1_1.place(relx=0.467, rely=0.535, height=20, relwidth=0.2)
        self.Entry1_1_1_1.configure(background="white")
        self.Entry1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1_1.configure(foreground="#000000")
        self.Entry1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1_1.configure(insertbackground="black")
        self.Entry1_1_1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1_1_1.configure(selectforeground="black")

        self.Label2_2_1_1 = tk.Label(self.top)
        self.Label2_2_1_1.place(relx=0.307, rely=0.642, height=22, width=76)
        self.Label2_2_1_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1_1.configure(anchor='w')
        self.Label2_2_1_1.configure(background="#d9d9d9")
        self.Label2_2_1_1.configure(compound='left')
        self.Label2_2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1_1.configure(font="-family {Times New Roman} -size 14")
        self.Label2_2_1_1.configure(foreground="#000000")
        self.Label2_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1_1.configure(highlightcolor="black")
        self.Label2_2_1_1.configure(text='''Wspace''')

        self.Entry1_1_1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1_1_1.place(relx=0.467, rely=0.642, height=20
                , relwidth=0.2)
        self.Entry1_1_1_1_1.configure(background="white")
        self.Entry1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1_1_1.configure(foreground="#000000")
        self.Entry1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1_1_1.configure(insertbackground="black")
        self.Entry1_1_1_1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1_1_1_1.configure(selectforeground="black")

        self.Label2_2_1_1_1 = tk.Label(self.top)
        self.Label2_2_1_1_1.place(relx=0.307, rely=0.749, height=22, width=76)
        self.Label2_2_1_1_1.configure(activebackground="#f9f9f9")
        self.Label2_2_1_1_1.configure(anchor='w')
        self.Label2_2_1_1_1.configure(background="#d9d9d9")
        self.Label2_2_1_1_1.configure(compound='left')
        self.Label2_2_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_2_1_1_1.configure(font="-family {Times New Roman} -size 14")
        self.Label2_2_1_1_1.configure(foreground="#000000")
        self.Label2_2_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_2_1_1_1.configure(highlightcolor="black")
        self.Label2_2_1_1_1.configure(text='''Hspace''')

        self.Entry1_1_1_1_1_1 = tk.Entry(self.top)
        self.Entry1_1_1_1_1_1.place(relx=0.467, rely=0.749, height=20
                , relwidth=0.2)
        self.Entry1_1_1_1_1_1.configure(background="white")
        self.Entry1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1_1_1_1_1.configure(font="TkFixedFont")
        self.Entry1_1_1_1_1_1.configure(foreground="#000000")
        self.Entry1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1_1_1_1_1.configure(highlightcolor="black")
        self.Entry1_1_1_1_1_1.configure(insertbackground="black")
        self.Entry1_1_1_1_1_1.configure(selectbackground="#c4c4c4")
        self.Entry1_1_1_1_1_1.configure(selectforeground="black")

        def properties_to_plot():
            global dictionary_params
            dictionary_params = {

               'left' : float(self.Entry1.get()) ,
               'right': float(self.Entry1_1.get()) ,
               'bottom' : float(self.Entry1_1_1.get()) ,
               'top' : float(self.Entry1_1_1_1.get()) ,
               'wspace' : float(self.Entry1_1_1_1_1.get()) ,
               'hspace' : float(self.Entry1_1_1_1_1_1.get()) 

            }

            try:
               txt_file = open('dictionary_params.txt', 'wt')
               txt_file.write(str(dictionary_params))
               txt_file.close()
  
            except:
                tk.messagebox.showerror("Error" , "Unable to write to file !")

            

        self.Button1 = tk.Button(self.top , command=properties_to_plot)
        self.Button1.place(relx=0.275, rely=0.878, height=34, width=267)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#73a7ce")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Times New Roman} -size 12 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Properties to Plot''')

def start_up():
    edit_params_support.main()

if __name__ == '__main__':
    edit_params_support.main()




