# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 20, 2022 10:36:08 PM EEST  platform: Windows NT

import sys
import tkinter.ttk as ttk
from tkinter.constants import *
import subplot_properties
from tkinter import messagebox
import tkinter as tk

def main(*args):
   '''Main entry point for the application.'''
   global root
   try:
        if root.state() == "normal": 
            root.focus()
   except :
    root = tk.Tk()
    def on_closing():
     if tk.messagebox.askokcancel("Quit Subplot Properties", "Do you want to quit?"):
        root.destroy()
    root.protocol( 'WM_DELETE_WINDOW' , on_closing)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = subplot_properties.Toplevel1(_top1)
    root.mainloop()


if __name__ == '__main__':
    subplot_properties.start_up()


def destroy_window():
   try:
     #'root' in locals() or 'root' in globals():
        root.destroy()
   except :
        tk.messagebox.showerror("Error" , "Please set chart properties !") 